# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a251faf97128cbdd88e9988902b41de7867ec18a7a9af7d18c2a134370fcd802bd7f17fb66787411f881d85372f2ea85e716afddde74f4baf22e35ccbfa97520

test:
  secret_key_base: f3e88dc954224a3abf4f309a0f401c3c384efcb86c4f11d831531a1fc15b37ba2f7623a4f2a7f4bd48f4fdf7771ceebe95315c96f9a25cfc65f3a09d98a7d6e0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
